version: '3.3'

services:
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2017-latest
    #image: mcr.microsoft.com/mssql/server:2017-CU11-ubuntu
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "passw0rd"
    ports:
      - 3306:3306
    volumes:
      - my-volume:/var/opt/mssql
      
volumes:
  my-volume: